app = 'animations'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  processes = ['app']

[[vm]]
  size = 'performance-4x'
  processes = ['worker']
