# fly.toml app configuration file generated for animations on 2024-11-04T10:12:17-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'animations'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512mb"
