app = 'animations'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = "1024mb"
